Import(['env', 'target'])

env.Append(CPPPATH=['.', '../grammar'])
env.Append(CCFLAGS="-g -O0")

cgrammar   = env.Antlr('cparser.g')
cgrammarlib = env.Library('cgrammar', [cgrammar, 'Support.cpp', 'Dictionary.cpp'])

gnmgrammar    = env.Antlr('genom.g', ANTLRSUPER=File('cparser.g'))
gnm_sources = [ x for x in gnmgrammar if x.path.rfind(".cpp") != -1 ]
supportlib = env.Library('support', 
        ['typebuilder.cpp', 'type.cpp', 'typesolver.cpp', 'registry.cpp', 'genomreader.cpp', gnm_sources])

typeshow = env.Program('typeshow', 
        source = Split('typeshow.cpp'),
        LIBS=['support', 'cgrammar', 'antlr'], 
        LIBPATH = ['.', '../grammar'],
        RPATH = [target.abspath])

env.Default( typeshow )
env.Export('typeshow')
env.Install(target, typeshow)
env.SConscript('test/SConscript')

