Import('target')


env = Environment()
env.Append(CPPPATH=['.', '../grammar'])
env.Append(CCFLAGS="-g -O0")

supportlib = env.Library('support', 
        source = Split('typebuilder.cpp type.cpp typesolver.cpp registry.cpp'))

typeshow = env.Program('typeshow', 
        source = Split('typeshow.cpp'),
        LIBS=['grammar', 'antlr', 'support'], 
        LIBPATH = ['.', '../grammar'],
        RPATH = [target.abspath])

env.Default( typeshow )
env.Export('typeshow')
env.Install(target, typeshow)
env.SConscript('test/SConscript')

