Import(['env', 'target'])

env.Append(CPPPATH="/usr/include/libxml2")
env.Append(LIBPATH=['.'])

typelib = env.Library('typelib', ['type.cpp', 'typebuilder.cpp', 'registry.cpp'])

inspect = env.Program('typelib-inspect', ['inspect.cpp'], LIBS=['libxml2','typelib'])

env.Default( inspect )
env.Install(target, inspect)

