Import(['env', 'target'])

env.Append(CPPPATH=['.', '../typelib'])

cgrammar      = env.Antlr('cparser.g')
cgrammarlib   = env.Library('cgrammar', [cgrammar, 'Support.cpp', 'Dictionary.cpp'])

gnmgrammar    = env.Antlr('genom.g', ANTLRSUPER=File('cparser.g'))
gnm_sources = [ x for x in gnmgrammar if x.path.rfind(".cpp") != -1 ]

supportlib    = env.Library('genomsupport', 
                    ['typesolver.cpp', 'genommodule.cpp', 'preprocess.cpp', gnm_sources])

reader        = env.Program('genom-reader', 
                    source = 'genom-reader.cpp',
                    LIBS=['genomsupport', 'cgrammar', 'antlr', 'typelib', 'xml2'], 
                    LIBPATH = ['.', '../typelib'],
                    RPATH = [target.abspath])

env.Default( reader )
env.Export('reader')
env.Install(target, reader)
env.SConscript('test/SConscript')

